### ISSUE TITLE
左右拖动分类无效的BUG

### ISSUE THREAD

**Issue by ibenchu** [notadd/content#28]
![image](https://cloud.githubusercontent.com/assets/15061934/24795007/6d2e0302-1bba-11e7-8471-373316185111.png)
![image](https://cloud.githubusercontent.com/assets/15061934/24795014/7215ae1a-1bba-11e7-9d26-a7b13d2ec7dd.png)
![image](https://cloud.githubusercontent.com/assets/15061934/24795021/76961cae-1bba-11e7-8a4e-3b6fdf53e2f5.png)

**Comment by twilroad** [comment]
留待后续解决
